### ISSUE TITLE
`preact build` not working after upgrade to preactX

### ISSUE THREAD

**Issue by untitledlt** [preactjs/preact#1942]
- preact: 10.0.0-rc.3
- preact-cli:  3.0.0-rc.1
- node: v10.14.2

Here's what i'm getting after `npm build`:

```
✖ ERROR ./index.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/usr/local/lib/node_modules/preact-cli/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/usr/local/lib/node_modules/preact-cli/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at api (/usr/local/lib/node_modules/preact-cli/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js:19:7)
    at /usr/local/lib/node_modules/preact-cli/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at ./node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (./node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (./node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (./node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (./node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (./node_modules/babel-loader/lib/index.js:173:20)
✖ ERROR undefined
```

`npm run` works fine.

**Comment by SolarLiner** [comment]
The new version of Preact CLI uses Babel 7.x, but your project depends on Babel 6.x - so you need to update all Babel dependencies to use the new version.

**Comment by JoviDeCroock** [comment]
This seems resolved, feel free to reopen if this is not the case but I can confirm that @SolarLiner seems right.
