### ISSUE TITLE
Typescript error after upgrading to 10.x

### ISSUE THREAD

**Issue by gigamesh** [preactjs/preact#2089]
I'm working with a project that is on preact 8.4.2 and I want to upgrade to the latest version in order to use lazy route loading. However, doing so results in this typescript error when trying to build/run. Any ideas?:

```
export NODE_ENV=development && webpack-dev-server  --progress --colors --config ./webpack/webpack.dev.config.js

Node environment: DEVELOPMENT
Build [==                  ] 10% ( 10% building 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /leftfield/iowa/src
ℹ ｢wds｣: 404s will fallback to /index.html
Build [==================  ] 90% (4.1s) module a 94% after seal/leftfield/iowa/node_modules/typescript/lib/typescript.js:86995
                throw e;
                ^

TypeError: Cannot read property 'get' of undefined
    at getSymbol (/leftfield/iowa/node_modules/typescript/lib/typescript.js:31682:38)
    at getNameFromJsxElementAttributesContainer (/leftfield/iowa/node_modules/typescript/lib/typescript.js:47742:68)
    at getJsxElementPropertiesName (/leftfield/iowa/node_modules/typescript/lib/typescript.js:47774:20)
    at getJsxPropsTypeFromClassType (/leftfield/iowa/node_modules/typescript/lib/typescript.js:47004:40)
    at getEffectiveFirstArgumentForJsxSignature (/leftfield/iowa/node_modules/typescript/lib/typescript.js:46954:122)
    at checkApplicableSignatureForJsxOpeningLikeElement (/leftfield/iowa/node_modules/typescript/lib/typescript.js:48878:29)
    at checkApplicableSignature (/leftfield/iowa/node_modules/typescript/lib/typescript.js:48884:24)
    at chooseOverload (/leftfield/iowa/node_modules/typescript/lib/typescript.js:49225:26)
    at resolveCall (/leftfield/iowa/node_modules/typescript/lib/typescript.js:49177:26)
    at resolveJsxOpeningLikeElement (/leftfield/iowa/node_modules/typescript/lib/typescript.js:49755:20)
    at resolveSignature (/leftfield/iowa/node_modules/typescript/lib/typescript.js:49781:28)
    at getResolvedSignature (/leftfield/iowa/node_modules/typescript/lib/typescript.js:49804:26)
    at checkJsxOpeningLikeElementOrOpeningFragment (/leftfield/iowa/node_modules/typescript/lib/typescript.js:47929:27)
    at checkJsxSelfClosingElementDeferred (/leftfield/iowa/node_modules/typescript/lib/typescript.js:47485:13)
    at /leftfield/iowa/node_modules/typescript/lib/typescript.js:56279:25
    at Map.forEach (<anonymous>)
```

**Comment by andrewiggins** [comment]
Hi @gigamesh. A quick Google search led me to the following two issues. Any chance they are helpful? Looks like a TypeScript bug that was fixed in TS. What version of TS are you using? Could you try upgrading TS?

Microsoft/TypeScript#30153
developit/microbundle#407

**Comment by gigamesh** [comment]
@andrewiggins Thanks for the response.

It's possible the latest version of typescript fixes this, but I've been avoiding upgrading that because it results in a _different_ error, so I'm going to try to tackle that one. Thanks!
