### ISSUE TITLE
Jest, Preact and enzyme throwing an error

### ISSUE THREAD

**Issue by djforth** [preactjs/preact#2226]
So I'm getting the following error:
```
Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

      3 | import Adapter from 'enzyme-adapter-preact-pure';
      4 | console.log('Enzyme>>>>>', configure);
    > 5 | console.log('Preact >>>>', Adapter);
        |                                                       ^
      6 | configure({ adapter: new Adapter() });
      7 | 

      at ../../node_modules/preact/compat/dist/compat.js:1:469
      at Object.<anonymous> (../../node_modules/preact/compat/dist/compat.js:1:611)
      at Object.<anonymous> (__tests__/enzyme_setup.js:5:55)
```
The versions i have are so:

```
"preact": "^10.1.1",
"preact-render-to-string": "^5.1.3",
"enzyme": "^3.8.0",
"enzyme-adapter-preact-pure": "^2.2.0",
"jest": "^24.9.0",
"jest-enzyme": "^7.1.2",
```

Jest config has the this:

```
"moduleNameMapper": {
    "@djforth/ajax-es6-fp/fetch": "<rootDir>/__tests__/__mocks__/@djforth/ajax-es6-fp/fetch",
    "@djforth/geolocation_helper": "<rootDir>/__tests__/__mocks__/@djforth/geolocation_helper",
    "@djforth/viewport-detection-fp": "<rootDir>/__tests__/__mocks__/@djforth/viewport-detection-fp",
    "@morsedigital/i18n_helper": "<rootDir>/__tests__/__mocks__/@morsedigital/i18n_helper",
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__tests__/__mocks__/fileMock.js",
    "\\.(css|less|scss)$": "<rootDir>/__tests__/__mocks__/styleMock.js"
  },
```

Enzyme set up like so:

```
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-preact-pure';

configure({ adapter: new Adapter() });
```
The application works fine and if I set my tests to use react instead of preact they run fine.  Is there something I'm missing or is there a bug?

**Comment by robertknight** [comment]
>  Is there something I'm missing or is there a bug?

There are a lot of different pieces involved here (your code, Jest, various extra Preact/React libraries, mocks). It will help a lot if you can try to isolate the problem by removing some of those elements.

**Comment by djforth** [comment]
Ok I'll try to isolate the problem to narrow it down a bit

**Comment by marvinhagemeister** [comment]
Closing, because we haven't heard back from the issue reporter, so we're assuming that this has been fixed. Happy to re-open if this issue still persists.
