### ISSUE TITLE
preact hooks SSR doesn't work in MJS

### ISSUE THREAD

**Issue by dfabulich** [preactjs/preact#2520]
### Reproduction

https://github.com/dfabulich/preact-hooks-ssr-esm

It's a simple repo depending on `preact`, `preact-render-to-string`, and `htm`, with two scripts, `index.js` (using CommonJS) and `index.mjs` (using ES modules), that are designed to be two versions of the same server-side rendering hooks sample.

I'm using Node v14.1.0.

### Steps to reproduce

Check out that repo on github and `npm install`. You can run `node index` and it will print `<div class="foo">0</div>`. Now run `node index.mjs`.

### Expected Behavior

It should print `<div class="foo">0</div>` just like the CJS version does

### Actual Behavior

```
Error: Hook can only be invoked from render methods.
    at Object.n.__h (file:///tmp/preact-hooks-ssr-esm/node_modules/preact/debug/dist/debug.mjs:1:5847)
    at v (file:///tmp/preact-hooks-ssr-esm/node_modules/preact/hooks/dist/hooks.mjs:1:117)
    at p (file:///tmp/preact-hooks-ssr-esm/node_modules/preact/hooks/dist/hooks.mjs:1:272)
    at m (file:///tmp/preact-hooks-ssr-esm/node_modules/preact/hooks/dist/hooks.mjs:1:241)
    at Object.App (file:///tmp/preact-hooks-ssr-esm/index.mjs:10:28)
    at g (/tmp/preact-hooks-ssr-esm/node_modules/preact-render-to-string/dist/index.js:1:2233)
    at file:///tmp/preact-hooks-ssr-esm/index.mjs:14:13
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

**Comment by marvinhagemeister** [comment]
Was able to trace it down to lacking the `export` syntax in `package.json` of `preact-render-to-string`. On top of that the latest published version has a pretty outdated `mjs` file in the `dist` bundle which is broken.
