### ISSUE TITLE
error building with latest preact, next.js: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by srdjan** [preactjs/preact#2937]
### Reproduction

https://github.com/srdjan/next-repros

### Steps to reproduce

```
npm run build
```

### Expected Behavior

successful build

### Actual Behavior

> Build error occurred
{ Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._resolveFilename (/Users/srdjans/Code/next-repros/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/srdjans/Code/next-repros/node_modules/@prefresh/webpack/src/index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/srdjans/Code/next-repros/node_modules/@prefresh/next/src/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) code: 'MODULE_NOT_FOUND' }

**Comment by marvinhagemeister** [comment]
Looks like the canary builds of `nextjs` [inline webpack](https://github.com/vercel/next.js/commit/bddb02286fdcfb83fc97fa91df378cb6d92778e8) as a dependency. Therefore it won't show up in `node_modules` anymore.

Downgrading next to the latest stable build works fine.
