### ISSUE TITLE
Using @loadable/server with preact-render-to-string SSR not working

### ISSUE THREAD

**Issue by ethan-pearce** [preactjs/preact#3548]
We are currently trying to use `preact-render-to-string` with `@loadable/server`  and we get the following issue...

```
Error: [object Object] is not a valid HTML tag name in <[object Object] value="[object Object]">
    at replace (/sandbox/node_modules/preact-render-to-string/src/index.js:332:15)
    at __c (/sandbox/node_modules/preact-render-to-string/src/index.js:169:37)
    at y (/sandbox/node_modules/preact-render-to-string/src/index.js:46:21)
    at /sandbox/src/server.js:36:20
    at Layer.handle [as handle_request] (/sandbox/node_modules/express/lib/router/layer.js:95:5)
    at next (/sandbox/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/sandbox/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/sandbox/node_modules/express/lib/router/layer.js:95:5)
    at /sandbox/node_modules/express/lib/router/index.js:281:22
    at param (/sandbox/node_modules/express/lib/router/index.js:354:14)
```

Note this does not happen when we use renderToString from react/server, we will continue to investigate but if anyone has any ideas it would be much appreciated 

I have created a little Code Sandbox to make it easier to show the issue: https://codesandbox.io/s/summer-cloud-qhpg4l?file=/src/server.js 

Ref: https://github.com/preactjs/preact-render-to-string/issues/222

**Comment by JoviDeCroock** [comment]
I quickly looked at this through comparing the outputs of a raw and one with `extractor.collectChunks` what stands out to me is that we add a wrapping component that seems to be an empty function
