### ISSUE TITLE
createPortal is not working properly

### ISSUE THREAD

**Issue by Unluckynerd** [preactjs/preact#4073]
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

I'm rendering drawer web component using createPortal.When changing the route the following error is thrown. In preact app i'm used `react-router-dom`.

```
Uncaught Error: Undefined parent passed to render(), this is the second argument.
Check if the element is available in the DOM/has the correct id.
    at preact__WEBPACK_IMPORTED_MODULE_0__.options.__ (debug.js:89:1)
    at P (render.js:16:1)
    at e.componentWillUnmount (portals.js:23:1)
    at N (index.js:521:1)
    at N (index.js:531:1)
    at N (index.js:531:1)
    at N (index.js:531:1)
    at N (index.js:531:1)
    at N (index.js:531:1)
    at N (index.js:531:1)
```

**To Reproduce**

Lets Say I have two pages `Home` and `About`. I'm used my Drawer in About page. There's no error when changing from `Home` to `About` Page. But when changing from `About` from `Home` it throws an error and the page is Home page is rendered above `About` Page. I'm not sure what's the problem here but i'm pretty sure it is because using `createPortal` in different routes.
The wrapper is present in the DOM. I'm not used RenderInto in Home page. When the error throws the RenderInto doesn't even called / executed, tried with debugger. 

Note: createPortal works fine in `About` Page.

This is the code of createPortal written as functional Component

```
import { createPortal } from 'preact/compat';

export default function RenderInto({ into, children }) {
  let wrapper = document.querySelector(into) || null;

  return createPortal(children, wrapper);
}
```

and i'm used as

```
<RenderInto into="#drawer-wrapper">
  <my-drawer>
   *** Code **
  </my-drawer>
</RenderInto>
```

**Comment by marvinhagemeister** [comment]
Does an element with the selector `#drawer-wrapper` exist in the DOM?

**Comment by Unluckynerd** [comment]
Yes

**Comment by marvinhagemeister** [comment]
Is that a node created by Preact or something that already exists in the DOM? Asking because the error says that at the time the Portal tried to render, that element didn't exist. Might be that it was created at a later point in time. Can you share the code that's causing the issue?

**Comment by JoviDeCroock** [comment]
Closing due to inactivity, a reproduction would be very welcome if this pops up again
