### ISSUE TITLE
Aliasing React to Preact in Deno

### ISSUE THREAD

**Issue by adamzerner** [preactjs/preact#4247]
There is a section on the Getting Started page called "[Aliasing React to Preact](https://preactjs.com/guide/v10/getting-started#aliasing-react-to-preact)". There is no example for how to do this in a Deno project. So 1) I'd like to ask how to do so in a Deno project, and 2) I'd like to propose that a Deno example be added to "Aliasing React to Preact".

Context: I am using [Fresh](https://fresh.deno.dev/), am trying to use [Sandpack](https://sandpack.codesandbox.io), and get the following error when I do. This error is because Sandpack uses React's `useState` and Fresh uses Preact. I think (but am unsure) that what I need to do to resolve this is alias React to `preact/compat`.

```
TypeError: Cannot read properties of null (reading 'useState')
    at Module.n.useState (https://esm.sh/stable/react@18.2.0/denonext/react.mjs:2:6891)
    at Object.Za (https://esm.sh/v135/@codesandbox/sandpack-react@2.8.0/denonext/sandpack-react.mjs:690:7478)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3237)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2543)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:5050)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2543)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:5050)
```

As a guess, I tried doing:
```
"react": "npm:preact/compat",
"react-dom": "npm:preact/compat",
"react/jsx-runtime": "npm:preact/jsx-runtime"
```
in `imports` in `deno.json` but it didn't work.

**Comment by marvinhagemeister** [comment]
That sounds more like a sandpack issue. My guess is that it doesn't know about `deno.json` and never reads that file.

**Comment by adamzerner** [comment]
Maybe. So you're saying that:
```
"react": "npm:preact/compat",
"react-dom": "npm:preact/compat",
"react/jsx-runtime": "npm:preact/jsx-runtime"
```
in `deno.json` is in fact the correct way to alias React to Preact in Deno?

**Comment by rschristian** [comment]
With the `npm:` prefix, I'd think you should be using the dedicated compat package, i.e., `npm:@preact/compat`

`@preact/compat` is just a mirror of `preact/compat` but as a dedicated package (for fulfilling this sort of purpose)

**Comment by adamzerner** [comment]
@rschristian Gotcha, thanks for clarifying.

**Comment by adamzerner** [comment]
@marvinhagemeister @rschristian I think we can close this out. [This](https://github.com/preactjs/preact/issues/4247#issuecomment-1877996709) addressed my question.

**Comment by rschristian** [comment]
`npm:@preact/compat` worked then? Glad to hear

**Comment by adamzerner** [comment]
Actually, sorry, I think I moved to close this too soon. Neither:

```
{
  ...
  "imports": {
    "react": "npm:@preact/compat",
    "react-dom": "npm:@preact/compat",
    "react/jsx-runtime": "npm:@preact/jsx-runtime"
  },
}
```

nor

```
{
  ...
  "imports": {
    "react": "npm:preact/compat",
    "react-dom": "npm:preact/compat",
    "react/jsx-runtime": "npm:preact/jsx-runtime"
  },
}
```

in `deno.json` successfully resolve the issue I am having with Sandpack. When I closed this issue I had thought that the issue was with Sandpack, but now I don't believe that to be the case. In [this repo](https://github.com/adamzerner/preact-issue-demo) I was able to get Sandpack working with Preact + Vite. That makes me think that Sandpack does in fact work in a Preact app that successfully aliases React to Preact, and that the issue I am having in my Deno app is regarding the above approaches not successfully aliasing React to Preact.

To see if this issue is Sandpack-specific, I tried testing [React Bootstrap](https://react-bootstrap.github.io/) as well. I was not able to get it working. I've got:
```
"react-bootstrap": "npm:react-bootstrap",
"bootstrap": "npm:bootstrap"
```
in my `deno.json`. `import { Button } from "react-bootstrap";` and `<Button>Example</Button>` on a page lead to a bunch of errors:

```
An error occurred during route handling or page rendering.
Error: Invalid type passed to createElement(): [object Object]
    at a.__b (https://esm.sh/stable/preact@10.19.2/denonext/debug.js:23:9)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2611)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2543)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:5050)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2543)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:5050)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/ssr.js:1:52:
      1 │ import { useSSRSafeId, useIsSSR, SSRProvider } from '@react-aria/ssr';
        ╵                                                     ~~~~~~~~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/prop-types@15.8.1/node_modules/prop-types/index.js:9:24:
      9 │   var ReactIs = require('react-is');
        ╵                         ~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/prop-types@15.8.1/node_modules/prop-types/factoryWithTypeCheckers.js:10:22:
      10 │ var ReactIs = require('react-is');
         ╵                       ~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/prop-types@15.8.1/node_modules/prop-types/factoryWithTypeCheckers.js:11:21:
      11 │ var assign = require('object-assign');
         ╵                      ~~~~~~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/uncontrollable@7.2.1_react@18.2.0/node_modules/uncontrollable/lib/esm/uncontrollable.js:6:25:
      6 │ import { polyfill } from 'react-lifecycles-compat';
        ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:27:24:
      27 │ var Scheduler = require('scheduler');
         ╵                         ~~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/usePopper.js:4:23:
      4 │ import { dequal } from 'dequal';
        ╵                        ~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:1:18:
      1 │ import arrow from '@popperjs/core/lib/modifiers/arrow';
        ╵                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:2:26:
      2 │ import computeStyles from '@popperjs/core/lib/modifiers/computeStyles';
        ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:3:27:
      3 │ import eventListeners from '@popperjs/core/lib/modifiers/eventListeners';
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:4:17:
      4 │ import flip from '@popperjs/core/lib/modifiers/flip';
        ╵                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:5:17:
      5 │ import hide from '@popperjs/core/lib/modifiers/hide';
        ╵                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:6:19:
      6 │ import offset from '@popperjs/core/lib/modifiers/offset';
        ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:7:26:
      7 │ import popperOffsets from '@popperjs/core/lib/modifiers/popperOffsets';
        ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:8:28:
      8 │ import preventOverflow from '@popperjs/core/lib/modifiers/preventOverflow';
        ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:9:27:
      9 │ import { placements } from '@popperjs/core/lib/enums';
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] NPM package not found. [plugin deno-loader]

    ../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:10:32:
      10 │ import { popperGenerator } from '@popperjs/core/lib/popper-base';
         ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

An error occurred during route handling or page rendering.
An error occurred during route handling or page rendering.
Error: Build failed with 17 errors:
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:1:18: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:2:26: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:3:27: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:4:17: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:5:17: ERROR: [plugin: deno-loader] NPM package not found.
...
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.19.4/mod.js:1626:15)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1035:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.19.4/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.19.4/mod.js:1033:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1062:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.19.4/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.19.4/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.19.4/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1924:11
    at eventLoopTick (ext:core/01_core.js:182:7) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
Error: Build failed with 17 errors:
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:1:18: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:2:26: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:3:27: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:4:17: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:5:17: ERROR: [plugin: deno-loader] NPM package not found.
...
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.19.4/mod.js:1626:15)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1035:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.19.4/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.19.4/mod.js:1033:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1062:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.19.4/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.19.4/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.19.4/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1924:11
    at eventLoopTick (ext:core/01_core.js:182:7) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
Error: Build failed with 17 errors:
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:1:18: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:2:26: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:3:27: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:4:17: ERROR: [plugin: deno-loader] NPM package not found.
../../Library/Caches/deno/deno_esbuild/@restart/ui@1.6.6_react@18.2.0_react-dom@18.2.0__react@18.2.0/node_modules/@restart/ui/esm/popper.js:5:17: ERROR: [plugin: deno-loader] NPM package not found.
...
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.19.4/mod.js:1626:15)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1035:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.19.4/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.19.4/mod.js:1033:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1062:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.19.4/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.19.4/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.19.4/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1924:11
    at eventLoopTick (ext:core/01_core.js:182:7) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
```

So then, it looks to me like the issue is with aliasing React to Preact to Deno.

**Comment by marvinhagemeister** [comment]
This is more of a Deno issue rather than an issue with Preact. At the moment there is no support for deduplicating npm dependencies and aliasing `react` to `preact` with `npm:` specifiers.

**Comment by adamzerner** [comment]
@marvinhagemeister Is there a way to alias `react` to `preact` in a way other than using `npm:` specifiers?
